export default {
  'Wilson': 'Wilson',
  'Willow': 'Willow',
  'Wendy': 'Wendy',
  'Wolfgang': 'Wolfgang',
  'Woodie': 'Woodie',
  'Wickerbottom': 'Wickerbottom',
  'WX-78': 'WX-78',
  'Wes': 'Wes',
  'Maxwell': 'Maxwell',
  'Wigfrid': 'Wigfrid',
  'Webber': 'Webber',
  'Winona': 'Winona',
  'Wortox': 'Wortox',
  'Wormwood': 'Wormwood',
  'Warly': 'Warly',
  'Wurt': 'Wurt',
  'Walter': 'Walter',
  'Wanda': 'Wanda',
};
