name: DEV workflow

on:
  push:
    branches: [stage]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: yarn

    - name: Run test lint
      run: yarn lint

    - name: Stop process
      if: failure()
      run: exit 1

    - name: Build DEV
      run: yarn build:dev
      env:
        CI: true

    - name: Deploy to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        strip_components: 1
        source: "build"
        target: "/opt/dsp.be.wtf/"

    - name: recats ci
      run: curl -H "Content-Type:application/json" -X POST ${{ secrets.CI_ENDPOINT }} -d '{"telegramChatID":"${{ secrets.TELEGRAM_TO }}","owner":"bidease","repo":"dsp-front","branch":"stage","description":"#developer\nBuildTime - no build time"}'
