name: PROD workflow

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%FT%T')"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install deps
      run: yarn

    - name: Run test lint
      run: yarn lint

    - name: Stop process
      if: failure()
      run: exit 1

    - name: Build PROD
      run: REACT_APP_BUILD_TIME=${{ steps.date.outputs.date }} yarn build:prod
      env:
        CI: true

    - name: Deploy to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        strip_components: 1
        source: "build"
        target: "/opt/ui.bidease.com/"

    - name: recats ci
      run: curl -H "Content-Type:application/json" -X POST ${{ secrets.CI_ENDPOINT }} -d '{"telegramChatID":"${{ secrets.TELEGRAM_TO }}","owner":"bidease","repo":"dsp-front","branch":"master","description":"#production\nBuildTime - ${{ steps.date.outputs.date }}"}'
